name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0=h96cf925_1
  - aiobotocore=2.5.4=pyhd8ed1ab_0
  - aiohttp=3.8.5=py311h2725bcf_0
  - aioitertools=0.11.0=pyhd8ed1ab_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - arm_pyart=1.15.2=py311h2725bcf_0
  - arrow-cpp=11.0.0=h89a8245_2
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - aws-c-common=0.6.8=h6c40b1e_1
  - aws-c-event-stream=0.1.6=hcec6c5f_6
  - aws-checksums=0.1.11=h6c40b1e_2
  - aws-sdk-cpp=1.8.185=h1a8d504_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - basemap=1.3.8=py311h402d0fa_0
  - basemap-data=1.3.2=pyhd8ed1ab_3
  - blas=2.117=openblas
  - blas-devel=3.9.0=17_osx64_openblas
  - bokeh=3.2.2=pyhd8ed1ab_0
  - boltons=23.0.0=py311hecd8cb5_0
  - boost-cpp=1.73.0=hca72f7f_12
  - boto=2.49.0=py_0
  - botocore=1.31.17=pyhd8ed1ab_3
  - brotli=1.0.9=hb7f2c08_9
  - brotli-bin=1.0.9=hb7f2c08_9
  - brotlipy=0.7.0=py311h6c40b1e_1002
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.19.0=h6c40b1e_0
  - ca-certificates=2023.7.22=h8857fd0_0
  - cartopy=0.22.0=py311hab14417_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py311h6c40b1e_3
  - cftime=1.6.2=py311hd5badaa_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - conda=23.7.4=py311h6eed73b_0
  - conda-content-trust=0.1.3=py311hecd8cb5_0
  - conda-libmamba-solver=23.5.0=py311hecd8cb5_0
  - conda-package-handling=2.1.0=py311hecd8cb5_0
  - conda-package-streaming=0.8.0=py311hecd8cb5_0
  - contourpy=1.0.5=py311ha357a0b_0
  - cryptography=39.0.1=py311hf6deb26_2
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.2=py311h2725bcf_0
  - dask=2023.8.1=pyhd8ed1ab_0
  - dask-core=2023.8.1=pyhd8ed1ab_0
  - debugpy=1.6.7=py311hcec6c5f_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distributed=2023.8.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - fmt=9.1.0=ha357a0b_0
  - fonttools=4.42.1=py311h2725bcf_0
  - freetype=2.12.1=hd8bbffd_0
  - frozenlist=1.4.0=py311h2725bcf_0
  - fsspec=2023.6.0=pyh1a96a4e_0
  - geos=3.12.0=he965462_0
  - gflags=2.2.2=hb1e8313_1004
  - giflib=5.2.1=hb7f2c08_3
  - glog=0.5.0=h25b26a9_0
  - grpc-cpp=1.48.2=h4ed1731_1
  - h5netcdf=1.2.0=pyhd8ed1ab_0
  - h5py=3.9.0=py311hdb7e403_0
  - hdf4=4.2.13=h39711bb_2
  - hdf5=1.12.1=ha01d115_3
  - icu=58.2=h0a44026_3
  - idna=3.4=py311hecd8cb5_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - ipykernel=6.25.1=pyh5fb750a_0
  - ipython=8.14.0=pyhd1c38e8_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - jpeg=9e=hb7f2c08_3
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyter_client=8.3.1=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py311h6eed73b_0
  - kiwisolver=1.4.4=py311hcec6c5f_0
  - krb5=1.20.1=h428f121_1
  - lat_lon_parser=1.3.0=pyhd8ed1ab_0
  - lcms2=2.15=h29502cd_0
  - lerc=3.0=he9d5cce_0
  - libarchive=3.6.2=h29ab7a1_2
  - libblas=3.9.0=17_osx64_openblas
  - libboost=1.73.0=h3fa6bed_12
  - libbrotlicommon=1.0.9=hb7f2c08_9
  - libbrotlidec=1.0.9=hb7f2c08_9
  - libbrotlienc=1.0.9=hb7f2c08_9
  - libcblas=3.9.0=17_osx64_openblas
  - libcurl=8.1.1=hf20ceda_1
  - libcxx=16.0.6=hd57cbcb_0
  - libdeflate=1.17=hb664fd8_0
  - libedit=3.1.20221030=h6c40b1e_0
  - libev=4.33=h9ed2024_1
  - libevent=2.1.12=ha90c15b_1
  - libffi=3.4.4=hecd8cb5_0
  - libgfortran=5.0.0=12_3_0_h97931a8_1
  - libgfortran5=12.3.0=hbd3c1fe_1
  - libiconv=1.16=hca72f7f_2
  - liblapack=3.9.0=17_osx64_openblas
  - liblapacke=3.9.0=17_osx64_openblas
  - libmamba=1.4.1=h8c3233a_1
  - libmambapy=1.4.1=py311h8c3233a_1
  - libnetcdf=4.8.1=h9f5a9a2_4
  - libnghttp2=1.52.0=h9beae6a_1
  - libopenblas=0.3.23=openmp_h429af6e_0
  - libpng=1.6.39=h6c40b1e_0
  - libprotobuf=3.20.3=hfff2838_0
  - libsodium=1.0.18=hbcb3906_1
  - libsolv=0.7.22=h8346a28_0
  - libssh2=1.10.0=h04015c4_2
  - libthrift=0.15.0=h70b4b81_2
  - libtiff=4.5.0=hcec6c5f_2
  - libwebp=1.2.4=h70a068d_1
  - libwebp-base=1.2.4=h6c40b1e_1
  - libxml2=2.10.3=h930c0e2_0
  - libzip=1.8.0=h29ab7a1_1
  - llvm-openmp=16.0.6=hff08bdf_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.2=py311haa801a3_0
  - lz4-c=1.9.4=hcec6c5f_0
  - markupsafe=2.1.3=py311h2725bcf_0
  - matplotlib-base=3.7.1=py311h2bf763f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - msgpack-python=1.0.5=py311hd2070f0_0
  - multidict=6.0.4=py311h5547dcb_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - netcdf4=1.6.2=py311h42ba51d_0
  - numpy=1.25.2=py311h91b6869_0
  - numpy-base=1.25.2=py311hb3ec012_0
  - open-radar-data=0.0.5=pyhd8ed1ab_0
  - openblas=0.3.23=openmp_hbefa662_0
  - openssl=3.1.2=h8a1eda9_0
  - orc=1.7.4=h995b336_1
  - packaging=23.0=py311hecd8cb5_0
  - pandas=2.0.0=py311hd84f3f5_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.4.0=pyhd8ed1ab_0
  - pcre2=10.37=he7042d7_1
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py311hcec6c5f_0
  - pip=23.1.2=py311hecd8cb5_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - pluggy=1.0.0=py311hecd8cb5_1
  - pooch=1.7.0=pyha770c72_3
  - proj=8.2.1=hd69def0_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py311h5547dcb_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=11.0.0=py311hf41f4e6_1
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.4=py311h6c40b1e_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyopenssl=23.0.0=py311hecd8cb5_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyproj=3.4.1=py311h089a554_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py311hecd8cb5_0
  - python=3.11.4=hf27a42d_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python.app=3=py311h6c40b1e_0
  - python_abi=3.11=2_cp311
  - pytz=2023.3=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311h2725bcf_0
  - pyzmq=24.0.1=py311habfacb3_1
  - re2=2022.04.01=h96cf925_0
  - readline=8.2=hca72f7f_0
  - reproc=14.2.4=he9d5cce_1
  - reproc-cpp=14.2.4=he9d5cce_1
  - ruamel.yaml=0.17.21=py311h6c40b1e_0
  - s3fs=0.5.1=py_0
  - scipy=1.10.1=py311h939689b_2
  - setuptools=67.8.0=py311hecd8cb5_0
  - setuptools-scm=7.1.0=pyhd8ed1ab_0
  - setuptools_scm=7.1.0=hd8ed1ab_0
  - shapely=2.0.1=py311haf3dd0c_2
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h225ccf5_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.41.2=h6c40b1e_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - tk=8.6.12=h5d9f67b_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=py311hecd8cb5_0
  - tornado=6.3.3=py311h2725bcf_0
  - tqdm=4.65.0=py311h85bffb1_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py311hecd8cb5_0
  - utf8proc=2.6.1=h9ed2024_0
  - versioneer=0.29=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py311hecd8cb5_0
  - xarray=2023.8.0=pyhd8ed1ab_0
  - xarray-datatree=0.0.12=pyhd8ed1ab_0
  - xmltodict=0.13.0=pyhd8ed1ab_0
  - xradar=0.3.0=pyhd8ed1ab_0
  - xyzservices=2023.7.0=pyhd8ed1ab_0
  - xz=5.4.2=h6c40b1e_0
  - yaml=0.2.5=h0d85af4_2
  - yaml-cpp=0.7.0=he9d5cce_1
  - yarl=1.9.2=py311h2725bcf_0
  - zeromq=4.3.4=he49afe7_1
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h4dc903c_0
  - zstandard=0.19.0=py311h6c40b1e_0
  - zstd=1.5.5=hc035e20_0
  - pip:
      - absl-py==2.0.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - beautifulsoup4==4.12.2
      - bt==1.0.0
      - cachetools==5.3.2
      - fastjsonschema==2.19.0
      - ffn==1.0.0
      - flatbuffers==23.5.26
      - frozendict==2.3.8
      - gast==0.5.4
      - google-auth==2.23.4
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.59.2
      - html5lib==1.1
      - joblib==1.3.2
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.1
      - keras==2.14.0
      - libclang==16.0.6
      - llvmlite==0.41.1
      - lxml==4.9.3
      - markdown==3.5.1
      - ml-dtypes==0.2.0
      - multitasking==0.0.11
      - nbformat==5.9.2
      - numba==0.58.1
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pandas-datareader==0.10.0
      - pandas-ta==0.4.4b0
      - peewee==3.17.0
      - plotly==5.18.0
      - protobuf==4.25.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyprind==2.11.3
      - referencing==0.31.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rpds-py==0.13.0
      - rsa==4.9
      - scikit-learn==1.3.2
      - seaborn==0.13.0
      - simpy==4.1.1
      - soupsieve==2.5
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - webencodings==0.5.1
      - werkzeug==3.0.1
      - wrapt==1.14.1
      - yfinance==0.2.31
prefix: /usr/local/Caskroom/miniconda/base
